[theme]
base = "light"
primaryColor = "#004e82"
backgroundColor = "#F5F7F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "viewer"

[server]
maxUploadSize = 50
enableXsrfProtection = true
